// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Games",
    columns: [
      { name: "title", type: "string" },
      { name: "completion", type: "string" },
      { name: "platform", type: "string" },
      { name: "image", type: "string" },
      { name: "platinum", type: "bool" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Games = InferredTypes["Games"];
export type GamesRecord = Games & XataRecord;

export type DatabaseSchema = {
  Games: GamesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Michael-Pallister-s-workspace-30014i.eu-west-1.xata.sh/db/michaelpallister-dev",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
