name: Update game percentages

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: curl
      uses: wei/curl@master
      with:
        args: https://www.michaelpallister.dev/api/game
