name: Update strava data

on:
  schedule:
    - cron: '0 */8 * * *'  # every 8 hours

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://www.michaelpallister.dev/api/strava
